import Head from 'next/head'
import { Header } from '../components/Header'
import { Main } from '../components/Main'

export default function Home() {
  return (
      <>
        <Head>
          <title>Ignite Feed</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/images/ignite-logo.svg" />
        </Head>
        <Header />
        <Main />
      </>
  )
}
